ENV['COCOAPODS_DISABLE_STATS'] = 'true' # It's a sample app

use_frameworks!

platform :ios, '10.0'
swift_version = '5.0'

target 'DownloadToGo_Example' do
  pod 'DownloadToGo', :path => '..'
  
  pod 'PlayKit', '~> 3.18'
#  pod 'PlayKit', :path => '../../playkit-ios'
#  pod 'PlayKit', :git => 'https://github.com/kaltura/playkit-ios', :branch => 'develop'

  pod 'PlayKitProviders', '~> 1.7'
#  pod 'PlayKitProviders'  #, :path => '../../playkit-ios-providers'
  
  pod 'Toast', '~> 4.0.0'

  target 'DownloadToGo_Tests' do
    inherit! :search_paths
  end
end
