ENV['COCOAPODS_DISABLE_STATS'] = 'true' # It's a sample app

use_frameworks!

platform :ios, '9.0'
swift_version = '4.0'

target 'DownloadToGo_Example' do
  pod 'DownloadToGo', :path => '..'
  pod 'PlayKit'           , :path => '../../playkit-ios'
  pod 'PlayKitProviders'  , :path => '../../playkit-ios-providers'
  
  
  pod 'Toast', '~> 4.0.0'

  target 'DownloadToGo_Tests' do
    inherit! :search_paths

    pod 'Quick', '1.3.1'
    pod 'Nimble', '7.1.3'
  end
end
